theme: minima
description: Natália Oliveira's tech blog about software development and computer science for portuguese speakers.
author:
  name: Natália Oliveira
  email: nataliaferreiraoliveira1994@gmail.com
header_pages:
  - about.md
