theme: minima
# description: Um blog sobre desenvolvimento de software e ciência da computação em geral.
author:
  name: Natália Oliveira
  email: nataliaferreiraoliveira1994@gmail.com
header_pages:
  - about.md

minima:
  date_format: "%d/%m/%Y"

  social_links:
   - { platform: github,         user_url: "https://github.com/nfo94" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/nataliaferreiraoliveira/" }

languages:
  en:
    title: "A blog about software development and computer science in general."
    description: "A blog about software development and computer science in general."
    permalink: /en/:path/
  pt:
    title: "Um blog sobre desenvolvimento de software e ciência da computação em geral."
    description: "Um blog sobre desenvolvimento de software e ciência da computação em geral."
    permalink: /pt/:path/
